---
title: "National Survey Map"
author: "Selemani Ngwira"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


pacman::p_load(
  rio,           # to import data
  here,          # to locate files
  tidyverse,     # to clean, handle, and plot the data (includes ggplot2 package)
  sf,            # to manage spatial data using a Simple Feature format
  tmap,          # to produce simple maps, works for both interactive and static maps
  janitor,       # to clean column names
  OpenStreetMap, # to add OSM basemap in ggplot map
  spdep, # spatial statistics
  gganimate, # for animated maps, 
  caTools, 
  gifski
  )

library(magick)

```

## loading data set


```{r cars}
study_site<-import(
  here("data/Study site.xlsx"))


# loading Malawi shape file 

Malawi_shapefile<-st_read(
  here("data/mwi_admbnda_adm2_nso_hotosm_20230405.shp")) %>% 
  select(ADM2_EN) |> 
  rename(district = ADM2_EN)

lakes <- st_read(
  here("data/Water bodies.shp")) |> 
  select(name)
  


```

## Changing Lon and Atti col into geometry
```{r pressure, echo=FALSE}

# changing the coords system of lon and lat col
health_facility_sf<- health_facility_coord%>%
     sf::st_as_sf(coords = c("longitude", 
                             "latitude"), crs = 4326) 


study_site <- merge( Malawi_shapefile, study_site, by = "district", all.x = TRUE)

```


# Ploting Map



```{r}


# Set tmap to plot mode (not view mode)
tmap_mode("plot")

# Create the map object
study_map <- tm_shape(Malawi_shapefile) +
  tm_borders(col = "black", lwd = 1) +

  tm_shape(lakes) +
  tm_polygons(col = "lightblue", border.col = "lightblue") +

  tm_shape(study_site) +
  tm_polygons(
    col = "study status",
    palette = c("Study site" = "white", "Not study site" = "lightgreen"),
    title = "Study Status",
    border.col = "black",
    lwd = 0.8
  ) +

  tm_text("district", 
          size = 0.6, 
          col = "black", 
          fontface = "bold", 
          shadow = TRUE) 

  # tm_layout(
  #   title = "Study Sites",
  #   title.position = c("center", "top"),
  #   legend.outside = F,
  #   legend.title.size = 1.2,
  #   legend.text.size = 0.9,
  #   frame = FALSE,
  #   bg.color = "white",
  #   asp = 0
  # )

# Save as high-resolution image (e.g., PNG at 300 dpi)
tmap_save(
  study_map,
  filename = "Malawi_Study_Sites_Map.png",
  width = 10,
  height = 8,
  units = "in",
  dpi = 300
)

```

