structure(list(url = "https://dhis2.health.gov.mw/api/analytics.json?paging=false&dimension=pe:LAST_12_MONTHS&dimension=ou:z1xZdKntTSZ&outputIdScheme=NAME", 
    status_code = 409L, headers = structure(list(server = "nginx/1.14.0 (Ubuntu)", 
        date = "Fri, 22 Mar 2024 09:20:16 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-length` = "153", connection = "keep-alive", 
        `content-security-policy` = "frame-ancestors 'self' http://afg.duredemos.com http://41.87.6.53:8080/2.40 http://localhost http://localhost:3001 http://localhost:4200 http://localhost:3000;", 
        `cache-control` = "no-cache, private", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 409L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.14.0 (Ubuntu)", 
            date = "Fri, 22 Mar 2024 09:20:16 GMT", `content-type` = "application/json;charset=UTF-8", 
            `content-length` = "153", connection = "keep-alive", 
            `content-security-policy` = "frame-ancestors 'self' http://afg.duredemos.com http://41.87.6.53:8080/2.40 http://localhost http://localhost:3001 http://localhost:4200 http://localhost:3000;", 
            `cache-control` = "no-cache, private", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_dhis2.health.gov.mw", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"httpStatus\":\"Conflict\",\"httpStatusCode\":409,\"status\":\"ERROR\",\"message\":\"Organisation unit or organisation unit level is not valid\",\"errorCode\":\"E7143\"}"), 
    date = structure(1711099216, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.012279, 
    connect = 0.029261, pretransfer = 0.051131, starttransfer = 0.091772, 
    total = 0.09183)), class = "response")
